-- Calendar integrity hardening: authenticated writes, recoverable deletes and append-only history.
create table if not exists public.calendar_admins (
  email text primary key check (email = lower(email)),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.calendar_admins (email, active)
values
  ('josetomasayalams@gmail.com', true),
  ('scamussotomayor@gmail.com', true)
on conflict (email) do update set active = excluded.active;

alter table public.calendar_admins enable row level security;
revoke all on public.calendar_admins from anon, authenticated;

create or replace function public.is_calendar_admin()
returns boolean
language sql
stable
security definer
set search_path = public, auth
as $$
  select exists (
    select 1
    from public.calendar_admins
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
      and active = true
  );
$$;
revoke all on function public.is_calendar_admin() from public, anon;
grant execute on function public.is_calendar_admin() to authenticated;

alter table public.reservations
  add column if not exists deleted_at timestamptz;

create index if not exists reservations_active_dates_idx
  on public.reservations (start_date, end_date)
  where deleted_at is null;

create table if not exists public.calendar_change_log (
  id bigint generated by default as identity primary key,
  table_name text not null,
  record_id text not null,
  operation text not null check (operation in ('INSERT', 'UPDATE', 'DELETE')),
  actor_email text not null,
  before_data jsonb,
  after_data jsonb,
  changed_at timestamptz not null default now()
);

alter table public.calendar_change_log enable row level security;
revoke all on public.calendar_change_log from anon, authenticated;

create or replace function public.log_calendar_change()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  before_row jsonb;
  after_row jsonb;
  row_id text;
begin
  before_row := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  after_row := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  row_id := coalesce(after_row ->> 'id', before_row ->> 'id', 'unknown');
  insert into public.calendar_change_log (
    table_name, record_id, operation, actor_email, before_data, after_data
  ) values (
    tg_table_name,
    row_id,
    tg_op,
    lower(coalesce(auth.jwt() ->> 'email', current_user, 'system')),
    before_row,
    after_row
  );
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
revoke all on function public.log_calendar_change() from public, anon, authenticated;

drop trigger if exists reservations_change_log_trg on public.reservations;
create trigger reservations_change_log_trg
  after insert or update or delete on public.reservations
  for each row execute function public.log_calendar_change();

create or replace function public.protect_calendar_change_log()
returns trigger
language plpgsql
as $$
begin
  raise exception 'calendar_change_log is append-only';
end;
$$;
revoke all on function public.protect_calendar_change_log() from public, anon, authenticated;

drop trigger if exists calendar_change_log_no_update on public.calendar_change_log;
create trigger calendar_change_log_no_update
  before update on public.calendar_change_log
  for each row execute function public.protect_calendar_change_log();

drop trigger if exists calendar_change_log_no_delete on public.calendar_change_log;
create trigger calendar_change_log_no_delete
  before delete on public.calendar_change_log
  for each row execute function public.protect_calendar_change_log();

drop policy if exists "public read" on public.reservations;
drop policy if exists "public write" on public.reservations;
drop policy if exists "calendar admins read reservations" on public.reservations;
drop policy if exists "calendar admins insert reservations" on public.reservations;
drop policy if exists "calendar admins update reservations" on public.reservations;
drop policy if exists "calendar admins delete reservations" on public.reservations;

create policy "calendar admins read reservations"
  on public.reservations for select to authenticated
  using (public.is_calendar_admin());
create policy "calendar admins insert reservations"
  on public.reservations for insert to authenticated
  with check (public.is_calendar_admin());
create policy "calendar admins update reservations"
  on public.reservations for update to authenticated
  using (public.is_calendar_admin()) with check (public.is_calendar_admin());
create policy "calendar admins delete reservations"
  on public.reservations for delete to authenticated
  using (public.is_calendar_admin());

revoke all on public.reservations from anon;
grant select, insert, update, delete on public.reservations to authenticated;
